import type { ArchiveState, CommitInfo, FileNode, LanguageMeta, Project } from "./types";

export const LANGS = {
  ts: { label: "TypeScript", color: "#3178C6" },
  js: { label: "JavaScript", color: "#F0DB4F" },
  rust: { label: "Rust", color: "#DEA584" },
  python: { label: "Python", color: "#3776AB" },
  go: { label: "Go", color: "#00ADD8" },
  csharp: { label: "C#", color: "#9B4F96" },
  shell: { label: "Shell", color: "#89E051" },
} satisfies Record<string, LanguageMeta>;

export const OPENED_RANK = [
  "dotfiles",
  "memoir",
  "next-blog",
  "rust-cli",
  "design-tokens",
  "ml-experiments",
  "api-gateway",
  "scraper-bot",
  "portfolio-2021",
  "game-jam-2020",
];

export const COMMIT_RANK = [
  "memoir",
  "rust-cli",
  "dotfiles",
  "next-blog",
  "design-tokens",
  "api-gateway",
  "scraper-bot",
  "ml-experiments",
  "portfolio-2021",
  "game-jam-2020",
];

const c = (
  hash: string,
  msg: string,
  time: string,
  add: number,
  del: number,
  author = "you",
): CommitInfo => ({ hash, msg, time, add, del, author });

const tree = (name: string, type: FileNode["type"], children?: FileNode[]): FileNode => ({
  name,
  type,
  children,
});

const emptyArchive = (): ArchiveState => ({
  positioning: { filled: false, text: "" },
  tech: { filled: false, text: "" },
  deploy: { filled: false, text: "" },
  todos: { filled: false, text: "" },
});

export const PROJECTS: Project[] = [
  {
    id: "memoir",
    name: "memoir",
    path: "~/dev/apps/memoir",
    lang: "ts",
    pinned: true,
    description: "Local-first desktop app to remember every project on your machine.",
    lastOpened: "12 分钟前",
    lastCommit: "2 小时前",
    lastCommitMsg: "feat(archive): stream AI draft into review drawer",
    lastCommitHash: "a3f9c21",
    git: {
      tracked: true,
      state: "dirty",
      changes: 7,
      ahead: 1,
      behind: 0,
      branch: "main",
      remote: "github.com/you/memoir",
    },
    status: "active",
    tags: ["desktop", "tauri", "ai"],
    techStack: ["Tauri 2", "React", "TypeScript", "Vite", "SQLite", "DeepSeek API"],
    commits: [
      c("a3f9c21", "feat(archive): stream AI draft into review drawer", "2 小时前", 184, 22),
      c("7b1e004", "refactor: extract GitBadge + CompletenessRing", "5 小时前", 96, 140),
      c("e52d9af", "feat(overview): filter by status & tags", "昨天", 210, 14),
      c("1c8a7d3", "fix: scan worker leaks file handles on large repos", "2 天前", 18, 31),
    ],
    files: tree("memoir", "folder", [
      tree("src", "folder", [
        tree("routes", "folder", [tree("dashboard.tsx", "file"), tree("project-detail.tsx", "file")]),
        tree("features", "folder", [
          tree("project", "folder", [tree("ProjectCard.tsx", "file")]),
          tree("archive", "folder", [tree("ArchiveEditor.tsx", "file")]),
          tree("git", "folder", [tree("GitPanel.tsx", "file")]),
        ]),
        tree("store", "folder", [tree("useMemoirStore.ts", "file")]),
      ]),
      tree("src-tauri", "folder", [tree("src", "folder", [tree("main.rs", "file")])]),
      tree("package.json", "file"),
      tree("vite.config.ts", "file"),
    ]),
    archive: {
      positioning: {
        filled: true,
        text: "面向独立开发者的本机项目记忆库。统一查看所有代码项目的结构、Git 记录与文档,并为久远项目用 AI 自动生成档案。",
      },
      tech: {
        filled: true,
        text: "Tauri 2 + React + TypeScript,Vite 构建。元数据缓存在本地 SQLite。Git 信息通过 Rust 命令读取,AI 档案由 DeepSeek API 生成。",
      },
      deploy: {
        filled: true,
        text: "本地桌面应用,Tauri bundler 打包为 dmg / msi / AppImage。无服务端,所有数据留在本机。",
      },
      todos: {
        filled: true,
        text: "- [ ] 数据库迁移\n- [ ] Git 写操作\n- [ ] 聊天记录关联",
      },
    },
    docs: [
      { type: "file", name: "ARCHITECTURE.md", meta: "Markdown · 8.2 KB" },
      { type: "link", name: "DeepSeek API Docs", meta: "platform.deepseek.com" },
    ],
  },
  {
    id: "next-blog",
    name: "next-blog",
    path: "~/dev/web/next-blog",
    lang: "ts",
    pinned: true,
    description: "Personal MDX blog on Next.js 14 App Router.",
    lastOpened: "昨天",
    lastCommit: "4 天前",
    lastCommitMsg: "content: 写完《本地优先软件》长文",
    lastCommitHash: "b71f2e8",
    git: {
      tracked: true,
      state: "clean",
      changes: 0,
      ahead: 0,
      behind: 0,
      branch: "main",
      remote: "github.com/you/next-blog",
    },
    status: "active",
    tags: ["web", "nextjs", "mdx"],
    techStack: ["Next.js 14", "React", "MDX", "Tailwind", "Vercel"],
    commits: [
      c("b71f2e8", "content: 写完《本地优先软件》长文", "4 天前", 420, 6),
      c("3d99a14", "feat: RSS feed + sitemap", "1 周前", 88, 2),
      c("a012f5c", "style: dark mode typography pass", "2 周前", 64, 40),
      c("5e7c8b9", "fix: og image generation on edge runtime", "3 周前", 24, 11),
    ],
    files: tree("next-blog", "folder", [
      tree("app", "folder", [tree("page.tsx", "file"), tree("layout.tsx", "file")]),
      tree("content", "folder", [tree("local-first.mdx", "file"), tree("hello-world.mdx", "file")]),
      tree("tailwind.config.ts", "file"),
      tree("package.json", "file"),
    ]),
    archive: {
      positioning: { filled: true, text: "个人技术博客,记录本地优先软件、前端工程与设计的思考。" },
      tech: { filled: true, text: "Next.js 14 App Router + MDX,Tailwind 排版,部署在 Vercel。" },
      deploy: { filled: true, text: "push 到 main 自动部署到 Vercel,域名走 Cloudflare。" },
      todos: { filled: false, text: "" },
    },
    docs: [
      { type: "file", name: "README.md", meta: "Markdown · 2.4 KB" },
      { type: "link", name: "Vercel Dashboard", meta: "vercel.com/you/next-blog" },
    ],
  },
  {
    id: "rust-cli",
    name: "devlog",
    path: "~/dev/tools/devlog",
    lang: "rust",
    description: "A fast terminal devlog & time tracker, written in Rust.",
    lastOpened: "3 天前",
    lastCommit: "6 小时前",
    lastCommitMsg: "perf: avoid alloc in hot path of parser",
    lastCommitHash: "f0c4d92",
    git: {
      tracked: true,
      state: "clean",
      changes: 0,
      ahead: 2,
      behind: 0,
      branch: "main",
      remote: "github.com/you/devlog",
    },
    status: "active",
    tags: ["cli", "rust"],
    techStack: ["Rust", "clap", "serde", "ratatui"],
    commits: [
      c("f0c4d92", "perf: avoid alloc in hot path of parser", "6 小时前", 34, 58),
      c("cc81a07", "feat: TUI dashboard with ratatui", "2 天前", 512, 12),
    ],
    files: tree("devlog", "folder", [
      tree("src", "folder", [tree("main.rs", "file"), tree("parser.rs", "file"), tree("tui.rs", "file")]),
      tree("Cargo.toml", "file"),
    ]),
    archive: {
      ...emptyArchive(),
      positioning: { filled: true, text: "终端里的轻量 devlog 与时间记录工具,一条命令记录今天做了什么。" },
      deploy: { filled: true, text: "cargo install,或 GitHub Release 提供预编译二进制。" },
    },
    docs: [{ type: "file", name: "README.md", meta: "Markdown · 3.1 KB" }],
  },
  {
    id: "dotfiles",
    name: "dotfiles",
    path: "~/dotfiles",
    lang: "shell",
    description: "zsh, nvim, tmux & macOS defaults.",
    lastOpened: "今天",
    lastCommit: "3 天前",
    lastCommitMsg: "chore: update nvim lsp config",
    lastCommitHash: "22dd51a",
    git: {
      tracked: true,
      state: "clean",
      changes: 0,
      ahead: 0,
      behind: 0,
      branch: "main",
      remote: "github.com/you/dotfiles",
    },
    status: "active",
    tags: ["config", "shell"],
    techStack: ["Shell", "Neovim", "tmux", "zsh"],
    commits: [c("22dd51a", "chore: update nvim lsp config", "3 天前", 28, 12)],
    files: tree("dotfiles", "folder", [
      tree("nvim", "folder", [tree("init.lua", "file")]),
      tree(".zshrc", "file"),
      tree("Brewfile", "file"),
    ]),
    archive: {
      positioning: { filled: true, text: "个人开发环境配置集合,用于快速恢复 macOS 工作站。" },
      tech: { filled: true, text: "Shell + Lua 配置,Homebrew 管理依赖。" },
      deploy: { filled: true, text: "运行 bootstrap.sh 后 symlink 到 home 目录。" },
      todos: { filled: true, text: "- [ ] 整理 macOS defaults\n- [ ] 分离公司机器配置" },
    },
    docs: [{ type: "file", name: "README.md", meta: "Markdown · 1.8 KB" }],
  },
  {
    id: "ml-experiments",
    name: "ml-experiments",
    path: "~/dev/research/ml-experiments",
    lang: "python",
    description: "",
    lastOpened: "上周",
    lastCommit: "8 个月前",
    lastCommitMsg: "wip: try focal loss on imbalanced set",
    lastCommitHash: "6d2a9e0",
    git: {
      tracked: true,
      state: "dirty",
      changes: 23,
      ahead: 0,
      behind: 0,
      branch: "master",
      remote: "",
    },
    status: "active",
    tags: ["ml", "pytorch", "research"],
    techStack: ["Python", "PyTorch", "NumPy", "Jupyter"],
    commits: [c("6d2a9e0", "wip: try focal loss on imbalanced set", "8 个月前", 88, 12)],
    files: tree("ml-experiments", "folder", [
      tree("notebooks", "folder", [tree("eda.ipynb", "file"), tree("train.ipynb", "file")]),
      tree("src", "folder", [tree("data.py", "file"), tree("model.py", "file")]),
    ]),
    archive: emptyArchive(),
    docs: [],
  },
  {
    id: "api-gateway",
    name: "api-gateway",
    path: "~/dev/work/api-gateway",
    lang: "go",
    description: "Internal API gateway with rate limiting and auth.",
    lastOpened: "2 周前",
    lastCommit: "2 周前",
    lastCommitMsg: "feat: per-tenant rate limiter",
    lastCommitHash: "8e3b1aa",
    git: {
      tracked: true,
      state: "clean",
      changes: 0,
      ahead: 0,
      behind: 3,
      branch: "main",
      remote: "github.com/acme/api-gateway",
    },
    status: "active",
    tags: ["backend", "go", "work"],
    techStack: ["Go", "gRPC", "Redis", "Docker"],
    commits: [c("8e3b1aa", "feat: per-tenant rate limiter", "2 周前", 180, 24)],
    files: tree("api-gateway", "folder", [
      tree("cmd", "folder", [tree("gateway", "folder", [tree("main.go", "file")])]),
      tree("internal", "folder", [tree("auth.go", "file"), tree("proxy.go", "file")]),
    ]),
    archive: {
      ...emptyArchive(),
      positioning: { filled: true, text: "公司内部服务的统一入口,负责鉴权、限流与路由。" },
      tech: { filled: true, text: "Go + gRPC,限流计数走 Redis,容器化部署。" },
      todos: { filled: true, text: "- [ ] 拉取 origin/main\n- [ ] 补 e2e 测试" },
    },
    docs: [{ type: "link", name: "Confluence — Gateway 设计", meta: "acme.atlassian.net" }],
  },
  {
    id: "design-tokens",
    name: "design-tokens",
    path: "~/dev/libs/design-tokens",
    lang: "ts",
    description: "Shared design tokens, published to npm.",
    lastOpened: "1 周前",
    lastCommit: "1 周前",
    lastCommitMsg: "feat: add semantic color aliases",
    lastCommitHash: "d4a1c77",
    git: {
      tracked: true,
      state: "clean",
      changes: 0,
      ahead: 0,
      behind: 0,
      branch: "main",
      remote: "github.com/you/design-tokens",
    },
    status: "active",
    tags: ["library", "design", "ts"],
    techStack: ["TypeScript", "Style Dictionary", "npm"],
    commits: [c("d4a1c77", "feat: add semantic color aliases", "1 周前", 64, 10)],
    files: tree("design-tokens", "folder", [
      tree("tokens", "folder", [tree("color.json", "file"), tree("space.json", "file")]),
      tree("build.ts", "file"),
    ]),
    archive: {
      ...emptyArchive(),
      positioning: { filled: true, text: "跨项目共享的设计 token 源,产出 CSS 变量与 TS 类型。" },
      tech: { filled: true, text: "Style Dictionary 构建,发布到 npm。" },
      deploy: { filled: true, text: "tag 触发 GitHub Action 自动发版。" },
    },
    docs: [{ type: "link", name: "npm — @you/design-tokens", meta: "npmjs.com" }],
  },
  {
    id: "scraper-bot",
    name: "scraper-bot",
    path: "~/dev/scripts/scraper-bot",
    lang: "python",
    description: "Scheduled scraper that watches a few sites.",
    lastOpened: "上个月",
    lastCommit: "5 周前",
    lastCommitMsg: "fix: retry failed selectors",
    lastCommitHash: "980d2ff",
    git: {
      tracked: true,
      state: "dirty",
      changes: 4,
      ahead: 0,
      behind: 0,
      branch: "main",
      remote: "github.com/you/scraper-bot",
    },
    status: "archived",
    tags: ["script", "python"],
    techStack: ["Python", "BeautifulSoup", "cron"],
    commits: [c("980d2ff", "fix: retry failed selectors", "5 周前", 22, 8)],
    files: tree("scraper-bot", "folder", [tree("main.py", "file"), tree("requirements.txt", "file")]),
    archive: {
      ...emptyArchive(),
      positioning: { filled: true, text: "定时抓取公开页面的小脚本,用于早期数据探索。" },
    },
    docs: [],
  },
  {
    id: "portfolio-2021",
    name: "portfolio-2021",
    path: "~/dev/archive/portfolio-2021",
    lang: "js",
    description: "",
    lastOpened: "4 个月前",
    lastCommit: "从未",
    lastCommitMsg: "",
    lastCommitHash: "",
    git: {
      tracked: false,
      state: "clean",
      changes: 0,
      ahead: 0,
      behind: 0,
      branch: "",
      remote: "",
    },
    status: "archived",
    tags: ["web", "old"],
    techStack: ["HTML", "CSS", "jQuery"],
    commits: [],
    files: tree("portfolio-2021", "folder", [tree("index.html", "file"), tree("style.css", "file")]),
    archive: emptyArchive(),
    docs: [],
  },
  {
    id: "game-jam-2020",
    name: "game-jam-2020",
    path: "~/dev/archive/game-jam-2020",
    lang: "csharp",
    description: "48-hour Unity prototype from an old game jam.",
    lastOpened: "半年以前",
    lastCommit: "2 年前",
    lastCommitMsg: "initial jam build",
    lastCommitHash: "f81aa22",
    git: {
      tracked: true,
      state: "clean",
      changes: 0,
      ahead: 0,
      behind: 0,
      branch: "main",
      remote: "",
    },
    status: "archived",
    tags: ["game", "unity", "old"],
    techStack: ["Unity", "C#"],
    commits: [c("f81aa22", "initial jam build", "2 年前", 400, 0)],
    files: tree("game-jam-2020", "folder", [
      tree("Assets", "folder", [tree("Scripts", "folder", [tree("Player.cs", "file")])]),
      tree("ProjectSettings", "folder", [tree("ProjectVersion.txt", "file")]),
    ]),
    archive: emptyArchive(),
    docs: [],
  },
];

export const SCAN_ROOTS = ["~/dev", "~/dotfiles", "~/work/acme"];
