import {
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowUp,
  BookOpen,
  Box,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  CircleDot,
  Clock,
  Code2,
  Copy,
  Database,
  Edit3,
  ExternalLink,
  File,
  FileCode,
  Folder,
  FolderOpen,
  GitBranch,
  GitCommitHorizontal,
  Globe2,
  Grid2X2,
  Inbox,
  Layers,
  Link2,
  List,
  Moon,
  Package,
  PanelTop,
  Plus,
  Search,
  Settings,
  Sparkles,
  Sun,
  Tag,
  TerminalSquare,
  X,
} from "lucide-react";
import type { LucideIcon, LucideProps } from "lucide-react";

const ICONS = {
  alert: AlertTriangle,
  archive: Archive,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  bookOpen: BookOpen,
  box: Box,
  check: Check,
  checkCircle: CheckCircle,
  chevronD: ChevronDown,
  chevronR: ChevronRight,
  clock: Clock,
  code: Code2,
  copy: Copy,
  database: Database,
  dotGrid: CircleDot,
  edit: Edit3,
  external: ExternalLink,
  file: File,
  fileCode: FileCode,
  folder: Folder,
  folderOpen: FolderOpen,
  gitBranch: GitBranch,
  gitCommit: GitCommitHorizontal,
  globe: Globe2,
  grid: Grid2X2,
  inbox: Inbox,
  layers: Layers,
  link: Link2,
  list: List,
  moon: Moon,
  package: Package,
  panel: PanelTop,
  plus: Plus,
  search: Search,
  settings: Settings,
  sort: List,
  sparkles: Sparkles,
  sun: Sun,
  tag: Tag,
  terminal: TerminalSquare,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

interface AppIconProps extends Omit<LucideProps, "ref"> {
  name: IconName;
}

export function AppIcon({ name, size = 16, strokeWidth = 1.7, ...props }: AppIconProps) {
  const Icon = ICONS[name] ?? ICONS.dotGrid;
  return <Icon size={size} strokeWidth={strokeWidth} {...props} />;
}

