/* ============================================================
   Memoir — Sample data (local developer projects)
   ============================================================ */

const LANGS = {
  ts:     { label: 'TypeScript', color: '#3178C6' },
  js:     { label: 'JavaScript', color: '#F0DB4F' },
  rust:   { label: 'Rust',       color: '#DEA584' },
  python: { label: 'Python',     color: '#3776AB' },
  go:     { label: 'Go',         color: '#00ADD8' },
  csharp: { label: 'C#',         color: '#9B4F96' },
  shell:  { label: 'Shell',      color: '#89E051' },
  swift:  { label: 'Swift',      color: '#F05138' },
};

// commit factory
const c = (hash, msg, time, add, del, author = 'you') => ({ hash, msg, time, add, del, author });

const tree = (name, type, children) => ({ name, type, children });

const PROJECTS = [
  {
    id: 'memoir',
    name: 'memoir',
    path: '~/dev/apps/memoir',
    lang: 'ts',
    pinned: true,
    description: 'Local-first desktop app to remember every project on your machine.',
    lastOpened: '12 分钟前',
    lastCommit: '2 小时前',
    lastCommitMsg: 'feat(archive): stream AI draft into review drawer',
    lastCommitHash: 'a3f9c21',
    git: { tracked: true, state: 'dirty', changes: 7, ahead: 1, behind: 0, branch: 'main', remote: 'github.com/you/memoir' },
    completeness: 92,
    status: 'active',
    tags: ['desktop', 'electron', 'ai'],
    techStack: ['Electron', 'React', 'TypeScript', 'Vite', 'SQLite', 'DeepSeek API'],
    commits: [
      c('a3f9c21', 'feat(archive): stream AI draft into review drawer', '2 小时前', 184, 22),
      c('7b1e004', 'refactor: extract GitBadge + CompletenessRing', '5 小时前', 96, 140),
      c('e52d9af', 'feat(overview): filter by status & tags', '昨天', 210, 14),
      c('1c8a7d3', 'fix: scan worker leaks file handles on large repos', '2 天前', 18, 31),
      c('9f4b6e1', 'chore: bump electron to 30, drop node-gyp', '3 天前', 7, 1203),
      c('44ad018', 'feat: SQLite cache for repo metadata', '4 天前', 312, 8),
    ],
    files: tree('memoir', 'folder', [
      tree('src', 'folder', [
        tree('main', 'folder', [
          tree('scanner.ts', 'file'), tree('git.ts', 'file'), tree('ipc.ts', 'file'),
        ]),
        tree('renderer', 'folder', [
          tree('App.tsx', 'file'), tree('Overview.tsx', 'file'), tree('ProjectDetail.tsx', 'file'),
          tree('components', 'folder', [ tree('Card.tsx', 'file'), tree('GitBadge.tsx', 'file'), tree('Ring.tsx', 'file') ]),
        ]),
        tree('ai', 'folder', [ tree('deepseek.ts', 'file'), tree('prompts.ts', 'file') ]),
      ]),
      tree('package.json', 'file'), tree('vite.config.ts', 'file'), tree('README.md', 'file'),
    ]),
    archive: {
      positioning: { filled: true, text: '面向独立开发者的本机项目记忆库。统一查看所有代码项目的结构、Git 记录与文档,并为久远项目用 AI 自动生成档案,解决「翻出三年前的项目完全看不懂」的痛点。' },
      tech: { filled: true, text: 'Electron + React + TypeScript,Vite 构建。元数据缓存在本地 SQLite。Git 信息通过 simple-git 读取,AI 档案由 DeepSeek API 流式生成。深色为默认主题,设计语言对标 Linear / Raycast。' },
      deploy: { filled: true, text: '本地桌面应用,electron-builder 打包为 .dmg / .exe。无服务端,所有数据留在本机 ~/Library/Application Support/memoir。DeepSeek API Key 存于系统钥匙串。' },
      todos: { filled: true, text: '- [ ] ⌘K 命令面板\n- [ ] 关联聊天记录(二期)\n- [x] 扫描大仓库的文件句柄泄漏\n- [ ] 浅色主题边角 case 走查' },
    },
    docs: [
      { type: 'file', name: 'ARCHITECTURE.md', meta: 'Markdown · 8.2 KB' },
      { type: 'file', name: 'design-brief.pdf', meta: 'PDF · 1.1 MB' },
      { type: 'link', name: 'Figma — Memoir UI Kit', meta: 'figma.com/file/…' },
      { type: 'link', name: 'DeepSeek API Docs', meta: 'platform.deepseek.com' },
    ],
  },
  {
    id: 'next-blog',
    name: 'next-blog',
    path: '~/dev/web/next-blog',
    lang: 'ts',
    pinned: true,
    description: 'Personal MDX blog on Next.js 14 App Router.',
    lastOpened: '昨天',
    lastCommit: '4 天前',
    lastCommitMsg: 'content: 写完《本地优先软件》长文',
    lastCommitHash: 'b71f2e8',
    git: { tracked: true, state: 'clean', changes: 0, ahead: 0, behind: 0, branch: 'main', remote: 'github.com/you/next-blog' },
    completeness: 78,
    status: 'active',
    tags: ['web', 'nextjs', 'mdx'],
    techStack: ['Next.js 14', 'React', 'MDX', 'Tailwind', 'Vercel'],
    commits: [
      c('b71f2e8', 'content: 写完《本地优先软件》长文', '4 天前', 420, 6),
      c('3d99a14', 'feat: RSS feed + sitemap', '1 周前', 88, 2),
      c('a012f5c', 'style: dark mode typography pass', '2 周前', 64, 40),
      c('5e7c8b9', 'fix: og image generation on edge runtime', '3 周前', 24, 11),
    ],
    files: tree('next-blog', 'folder', [
      tree('app', 'folder', [
        tree('page.tsx', 'file'), tree('layout.tsx', 'file'),
        tree('blog', 'folder', [ tree('[slug]', 'folder', [ tree('page.tsx', 'file') ]) ]),
      ]),
      tree('content', 'folder', [ tree('local-first.mdx', 'file'), tree('hello-world.mdx', 'file') ]),
      tree('tailwind.config.ts', 'file'), tree('package.json', 'file'), tree('README.md', 'file'),
    ]),
    archive: {
      positioning: { filled: true, text: '个人技术博客,记录本地优先软件、前端工程与设计的思考。' },
      tech: { filled: true, text: 'Next.js 14 App Router + MDX,Tailwind 排版,部署在 Vercel。' },
      deploy: { filled: true, text: 'push 到 main 自动部署到 Vercel,域名走 Cloudflare。' },
      todos: { filled: false, text: '' },
    },
    docs: [
      { type: 'file', name: 'README.md', meta: 'Markdown · 2.4 KB' },
      { type: 'link', name: 'Vercel Dashboard', meta: 'vercel.com/you/next-blog' },
    ],
  },
  {
    id: 'rust-cli',
    name: 'devlog',
    path: '~/dev/tools/devlog',
    lang: 'rust',
    description: 'A fast terminal devlog & time tracker, written in Rust.',
    lastOpened: '3 天前',
    lastCommit: '6 小时前',
    lastCommitMsg: 'perf: avoid alloc in hot path of parser',
    lastCommitHash: 'f0c4d92',
    git: { tracked: true, state: 'clean', changes: 0, ahead: 2, behind: 0, branch: 'main', remote: 'github.com/you/devlog' },
    completeness: 64,
    status: 'active',
    tags: ['cli', 'rust'],
    techStack: ['Rust', 'clap', 'serde', 'ratatui'],
    commits: [
      c('f0c4d92', 'perf: avoid alloc in hot path of parser', '6 小时前', 34, 58),
      c('cc81a07', 'feat: TUI dashboard with ratatui', '2 天前', 512, 12),
      c('2b6f140', 'feat: export to CSV / JSON', '5 天前', 140, 4),
    ],
    files: tree('devlog', 'folder', [
      tree('src', 'folder', [ tree('main.rs', 'file'), tree('parser.rs', 'file'), tree('tui.rs', 'file'), tree('store.rs', 'file') ]),
      tree('Cargo.toml', 'file'), tree('Cargo.lock', 'file'), tree('README.md', 'file'),
    ]),
    archive: {
      positioning: { filled: true, text: '终端里的轻量 devlog 与时间记录工具,一条命令记录今天做了什么。' },
      tech: { filled: false, text: '' },
      deploy: { filled: true, text: 'cargo install,或 GitHub Release 提供预编译二进制。' },
      todos: { filled: false, text: '' },
    },
    docs: [ { type: 'file', name: 'README.md', meta: 'Markdown · 3.1 KB' } ],
  },
  {
    id: 'ml-experiments',
    name: 'ml-experiments',
    path: '~/dev/research/ml-experiments',
    lang: 'python',
    description: '',
    lastOpened: '上周',
    lastCommit: '8 个月前',
    lastCommitMsg: 'wip: try focal loss on imbalanced set',
    lastCommitHash: '6d2a9e0',
    git: { tracked: true, state: 'dirty', changes: 23, ahead: 0, behind: 0, branch: 'master', remote: '' },
    completeness: 28,
    status: 'active',
    tags: ['ml', 'pytorch', 'research'],
    techStack: ['Python', 'PyTorch', 'NumPy', 'Jupyter'],
    commits: [
      c('6d2a9e0', 'wip: try focal loss on imbalanced set', '8 个月前', 88, 12),
      c('1aa7c34', 'add baseline resnet training loop', '9 个月前', 240, 0),
      c('90f1d5b', 'initial commit: dataset loaders', '11 个月前', 410, 0),
    ],
    files: tree('ml-experiments', 'folder', [
      tree('notebooks', 'folder', [ tree('eda.ipynb', 'file'), tree('train.ipynb', 'file') ]),
      tree('src', 'folder', [ tree('data.py', 'file'), tree('model.py', 'file'), tree('train.py', 'file') ]),
      tree('requirements.txt', 'file'),
    ]),
    archive: {
      positioning: { filled: false, text: '' },
      tech: { filled: false, text: '' },
      deploy: { filled: false, text: '' },
      todos: { filled: false, text: '' },
    },
    docs: [],
  },
  {
    id: 'api-gateway',
    name: 'api-gateway',
    path: '~/dev/work/api-gateway',
    lang: 'go',
    description: 'Internal API gateway with rate limiting and auth.',
    lastOpened: '2 周前',
    lastCommit: '2 周前',
    lastCommitMsg: 'feat: per-tenant rate limiter',
    lastCommitHash: '8e3b1aa',
    git: { tracked: true, state: 'clean', changes: 0, ahead: 0, behind: 3, branch: 'main', remote: 'github.com/acme/api-gateway' },
    completeness: 71,
    status: 'active',
    tags: ['backend', 'go', 'work'],
    techStack: ['Go', 'gRPC', 'Redis', 'Docker'],
    commits: [
      c('8e3b1aa', 'feat: per-tenant rate limiter', '2 周前', 180, 24),
      c('b2f9c01', 'fix: graceful shutdown drains conns', '3 周前', 40, 8),
    ],
    files: tree('api-gateway', 'folder', [
      tree('cmd', 'folder', [ tree('gateway', 'folder', [ tree('main.go', 'file') ]) ]),
      tree('internal', 'folder', [ tree('ratelimit.go', 'file'), tree('auth.go', 'file'), tree('proxy.go', 'file') ]),
      tree('Dockerfile', 'file'), tree('go.mod', 'file'),
    ]),
    archive: {
      positioning: { filled: true, text: '公司内部服务的统一入口,负责鉴权、限流与路由。' },
      tech: { filled: true, text: 'Go + gRPC,限流计数走 Redis,容器化部署。' },
      deploy: { filled: false, text: '' },
      todos: { filled: true, text: '- [ ] 拉取 origin/main(落后 3 个提交)\n- [ ] 补 e2e 测试' },
    },
    docs: [ { type: 'link', name: 'Confluence — Gateway 设计', meta: 'acme.atlassian.net' } ],
  },
  {
    id: 'design-tokens',
    name: 'design-tokens',
    path: '~/dev/libs/design-tokens',
    lang: 'ts',
    description: 'Shared design tokens, published to npm.',
    lastOpened: '1 周前',
    lastCommit: '1 周前',
    lastCommitMsg: 'feat: add semantic color aliases',
    lastCommitHash: 'd4a1c77',
    git: { tracked: true, state: 'clean', changes: 0, ahead: 0, behind: 0, branch: 'main', remote: 'github.com/you/design-tokens' },
    completeness: 83,
    status: 'active',
    tags: ['library', 'design', 'ts'],
    techStack: ['TypeScript', 'Style Dictionary', 'npm'],
    commits: [ c('d4a1c77', 'feat: add semantic color aliases', '1 周前', 64, 10) ],
    files: tree('design-tokens', 'folder', [
      tree('tokens', 'folder', [ tree('color.json', 'file'), tree('space.json', 'file') ]),
      tree('build.ts', 'file'), tree('package.json', 'file'),
    ]),
    archive: {
      positioning: { filled: true, text: '跨项目共享的设计 token 源,产出 CSS 变量与 TS 类型。' },
      tech: { filled: true, text: 'Style Dictionary 构建,发布到 npm。' },
      deploy: { filled: true, text: 'tag 触发 GitHub Action 自动发版。' },
      todos: { filled: false, text: '' },
    },
    docs: [ { type: 'link', name: 'npm — @you/design-tokens', meta: 'npmjs.com' } ],
  },
  {
    id: 'portfolio-2021',
    name: 'portfolio-2021',
    path: '~/dev/archive/portfolio-2021',
    lang: 'js',
    description: '',
    lastOpened: '4 个月前',
    lastCommit: '从未',
    lastCommitMsg: '',
    lastCommitHash: '',
    git: { tracked: false, state: 'clean', changes: 0, ahead: 0, behind: 0, branch: '', remote: '' },
    completeness: 18,
    status: 'archived',
    tags: ['web', 'old'],
    techStack: ['HTML', 'CSS', 'jQuery'],
    commits: [],
    files: tree('portfolio-2021', 'folder', [
      tree('index.html', 'file'), tree('style.css', 'file'), tree('main.js', 'file'),
      tree('img', 'folder', [ tree('hero.jpg', 'file') ]),
    ]),
    archive: {
      positioning: { filled: false, text: '' },
      tech: { filled: false, text: '' },
      deploy: { filled: false, text: '' },
      todos: { filled: false, text: '' },
    },
    docs: [],
  },
  {
    id: 'scraper-bot',
    name: 'scraper-bot',
    path: '~/dev/scripts/scraper-bot',
    lang: 'python',
    description: 'Scheduled scraper that watches a few sites.',
    lastOpened: '1 个月前',
    lastCommit: '5 周前',
    lastCommitMsg: 'fix: rotate user agents',
    lastCommitHash: '3c0af18',
    git: { tracked: true, state: 'dirty', changes: 4, ahead: 0, behind: 0, branch: 'main', remote: '' },
    completeness: 44,
    status: 'archived',
    tags: ['script', 'python'],
    techStack: ['Python', 'Playwright', 'cron'],
    commits: [ c('3c0af18', 'fix: rotate user agents', '5 周前', 22, 8) ],
    files: tree('scraper-bot', 'folder', [
      tree('scrape.py', 'file'), tree('config.yaml', 'file'), tree('requirements.txt', 'file'),
    ]),
    archive: {
      positioning: { filled: false, text: '' }, tech: { filled: true, text: 'Python + Playwright,cron 定时跑。' },
      deploy: { filled: false, text: '' }, todos: { filled: false, text: '' },
    },
    docs: [],
  },
  {
    id: 'game-jam-2020',
    name: 'game-jam-2020',
    path: '~/dev/archive/game-jam-2020',
    lang: 'csharp',
    description: '',
    lastOpened: '半年前',
    lastCommit: '从未',
    lastCommitMsg: '',
    lastCommitHash: '',
    git: { tracked: false, state: 'clean', changes: 0, ahead: 0, behind: 0, branch: '', remote: '' },
    completeness: 12,
    status: 'archived',
    tags: ['game', 'unity'],
    techStack: ['Unity', 'C#'],
    commits: [],
    files: tree('game-jam-2020', 'folder', [
      tree('Assets', 'folder', [ tree('Scripts', 'folder', [ tree('Player.cs', 'file'), tree('Enemy.cs', 'file') ]) ]),
      tree('ProjectSettings', 'folder', [ tree('settings.asset', 'file') ]),
    ]),
    archive: { positioning: { filled: false, text: '' }, tech: { filled: false, text: '' }, deploy: { filled: false, text: '' }, todos: { filled: false, text: '' } },
    docs: [],
  },
  {
    id: 'dotfiles',
    name: 'dotfiles',
    path: '~/dotfiles',
    lang: 'shell',
    description: 'zsh, nvim, tmux & macOS defaults.',
    lastOpened: '今天',
    lastCommit: '3 天前',
    lastCommitMsg: 'zsh: faster prompt with async git status',
    lastCommitHash: '5a7e210',
    git: { tracked: true, state: 'clean', changes: 0, ahead: 0, behind: 0, branch: 'main', remote: 'github.com/you/dotfiles' },
    completeness: 88,
    status: 'active',
    tags: ['config', 'shell'],
    techStack: ['Zsh', 'Neovim', 'tmux', 'Homebrew'],
    commits: [ c('5a7e210', 'zsh: faster prompt with async git status', '3 天前', 30, 14) ],
    files: tree('dotfiles', 'folder', [
      tree('zsh', 'folder', [ tree('.zshrc', 'file'), tree('aliases.zsh', 'file') ]),
      tree('nvim', 'folder', [ tree('init.lua', 'file') ]),
      tree('install.sh', 'file'), tree('README.md', 'file'),
    ]),
    archive: {
      positioning: { filled: true, text: '我的开发环境配置,一条命令在新机器上还原。' },
      tech: { filled: true, text: 'Zsh + Neovim + tmux,Homebrew bundle 管理依赖。' },
      deploy: { filled: true, text: 'clone 后跑 install.sh 软链到 home。' },
      todos: { filled: true, text: '- [x] async git prompt\n- [ ] 拆分 macOS / linux 分支' },
    },
    docs: [ { type: 'file', name: 'README.md', meta: 'Markdown · 1.8 KB' } ],
  },
];

const SCAN_DIRS = ['~/dev', '~/dotfiles', '~/work/acme'];

Object.assign(window, { PROJECTS, LANGS, SCAN_DIRS });
